# Generated by Django 5.1.7 on 2026-07-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0020_alter_member_dob_alter_member_renewal_date_and_more'),
        ('staff', '0002_staffmember_personal_trainer_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_slot', to='members.member')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint_slot', to='staff.staffmember')),
            ],
            options={
                'ordering': ['slot_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', False), ('staff__isnull', True)), models.Q(('member__isnull', True), ('staff__isnull', False)), _connector='OR'), name='fingerprintslot_exactly_one_owner')],
            },
        ),
    ]
