# Generated by Django 5.1.7 on 2026-07-15 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_member_dob_alter_member_renewal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invoice_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
