# Generated by Django 5.1.7 on 2026-08-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_member_created_at'),
        ('members', '0024_alter_member_created_at'),
    ]

    operations = [
    ]
